// Open-source licences: every package the app ships with its licence; tap one to read its text.
/**
 * M25 L2 (security audit #51): Settings › About › Open-source licences. The list comes from
 * src/legal/licences.ts (generated by scripts/licences.mjs). Fonts (Lora, Manrope: SIL Open Font
 * Licence 1.1) are in it through their @expo-google-fonts packages. A row opens the package's own
 * licence text when the list has it; otherwise the licence name and the package's address.
 */
import { useEffect, useState } from 'react';
import { BackHandler, Linking } from 'react-native';
import { FlatList } from '@/ui/lib/flat-list';
import { ScrollView } from '@/ui/lib/scroll-view';
import { Pressable } from '@/ui/lib/pressable';
import { Text } from '@/ui/lib/text';
import { Box } from '@/ui/lib/box';
import { PageHeader } from '@/ui/kit/PageHeader';
import { hit } from '@/design';
import { LICENCES, LICENCES_GENERATED, licenceText, type Licence } from '@/legal/licences';

const ROW = { minHeight: hit.min };

function Detail(props: { entry: Licence }): React.ReactElement {
  const text = licenceText(props.entry);
  const url = props.entry.url;
  return (
    <ScrollView className="flex-1 bg-background" contentContainerClassName="px-screen-x pb-section gap-row">
      <Text className="text-muted text-xs">{`Version ${props.entry.version} · ${props.entry.licence}`}</Text>
      {url && /^https?:\/\//.test(url) ? (
        <Pressable onPress={() => void Linking.openURL(url)} accessibilityRole="link" accessibilityLabel={`Open ${url}`} hitSlop={12} className="self-start">
          <Text className="text-accent text-xs font-bold">{url}</Text>
        </Pressable>
      ) : null}
      <Text className="text-text text-xs leading-[18px]" selectable>
        {text ?? `This package is published under the ${props.entry.licence} licence. Its full text is in the package itself${url ? ', at the address above' : ''}.`}
      </Text>
    </ScrollView>
  );
}

export default function LicencesScreen(): React.ReactElement {
  const [open, setOpen] = useState<Licence | undefined>();
  // Android's back closes an open licence first, then leaves the page.
  useEffect(() => {
    if (!open) return;
    const sub = BackHandler.addEventListener('hardwareBackPress', () => { setOpen(undefined); return true; });
    return () => sub.remove();
  }, [open]);
  if (open) {
    return (
      <>
      <PageHeader title={open.name} onBack={() => setOpen(undefined)} />
      <Detail entry={open} />
      </>
    );
  }
  return (
    <>
    <PageHeader title="Open-source licences" />
    <FlatList
      className="flex-1 bg-background"
      contentContainerClassName="px-screen-x pb-section"
      data={LICENCES as Licence[]}
      keyExtractor={(e) => `${e.name}@${e.version}`}
      ListHeaderComponent={
        <Text className="text-muted text-body mb-row">{`SocialNet is built with these ${LICENCES.length} open-source packages. Thank you to everyone who made them. List made ${LICENCES_GENERATED}.`}</Text>
      }
      renderItem={({ item }) => (
        <Pressable
          onPress={() => setOpen(item)}
          accessibilityRole="button"
          accessibilityLabel={`${item.name}, ${item.licence}`}
          className="flex-row items-center gap-row border-b border-border py-1.5"
          style={ROW}
        >
          <Box className="flex-1">
            <Text className="text-text text-body" numberOfLines={1}>{item.name}</Text>
            <Text className="text-muted text-xs">{`${item.version} · ${item.licence}`}</Text>
          </Box>
        </Pressable>
      )}
    />
    </>
  );
}
