#!/usr/bin/env node
// Copies the legal documents into a code file the app can show.
/**
 * Copies the three legal texts from `docs/legal/*.md` into `src/legal/texts.ts`, so the
 * app shows exactly what the documents say. `docs/` is not in the CI mirror and Metro
 * cannot import `.md`, hence a generated module. Run after editing a document:
 *
 *   node scripts/legal-sync.mjs
 *
 * M12 FR-005 (B1): the owner's answers live in the "Your text" column of
 * `docs/legal/placeholders.md`; each filled row replaces its `[PLACEHOLDER]` here, so the
 * documents stay templates and the app shows the answers. The cross-references between the
 * documents (`[SocialNet Privacy Policy]` …) are names, not fill-ins: their brackets go.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const DOCS = path.join('..', '..', 'docs', 'legal');
const FILES = { agreement: 'terms-of-service.md', privacy: 'privacy-policy.md', community: 'community-guidelines.md' };

/** `| \`[X]\` | what | where | answer |` rows with an answer. */
export function answers(md) {
  const out = {};
  for (const m of md.matchAll(/^\|\s*`(\[[^\]`]+\])`\s*\|[^|]*\|[^|]*\|\s*([^|]*?)\s*\|\s*$/gm)) if (m[2] !== '') out[m[1]] = m[2];
  return out;
}

const REFERENCES = /\[(SocialNet [^\]]+|Third-Party Information Sharing List|Personal Information Collection List)\]/g;

export function fill(text, values) {
  let t = text;
  for (const [k, v] of Object.entries(values)) t = t.split(k).join(v);
  return t.replace(REFERENCES, '$1');
}

const values = answers(readFileSync(path.join(DOCS, 'placeholders.md'), 'utf8'));
let out = '// Holds the user agreement, privacy policy and community rules text.\n';
out += '// GENERATED by scripts/legal-sync.mjs from docs/legal/*.md — edit the documents, not this file.\n\n';
out += 'export const LEGAL_TEXT = {\n';
for (const [id, file] of Object.entries(FILES)) {
  out += `  ${id}: ${JSON.stringify(fill(readFileSync(path.join(DOCS, file), 'utf8'), values))},\n`;
}
out += '} as const;\n';
writeFileSync(path.join('src', 'legal', 'texts.ts'), out);
// M25 SB (audit #17): the API's web pages (/privacy, /terms) show the SAME text, so the two cannot drift.
const API_OUT = path.join('..', 'api', 'src', 'pages', 'legal-texts.ts');
writeFileSync(API_OUT, out.replace(/^\/\/ Holds the user agreement, privacy policy and community rules text\.\n/, '// The same legal texts the app shows, for the web pages /privacy and /terms.\n'));
console.log(`legal-sync: wrote src/legal/texts.ts and ${API_OUT} (${Object.keys(FILES).length} documents, ${Object.keys(values).length} answers)`);
